In [1]:
%pip install randomuser

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: randomuser
  Building wheel for randomuser (pyproject.toml) ... done
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5105 sha256=12d513c91428eef782760bf9bbfc04f6945697383fb09a2c808370ed4f980bde
  Stored in directory: /Users/franciscofarfan/Library/Caches/pip/wheels/1b/79/19/d8c0d6163d7c537b588138c2ee5ff37dc915b5ae0420a6617e
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6
Note: you may need to restart the kernel to use updated packages.

In [4]:
from randomuser import RandomUser
import pandas as pd

In [5]:
r = RandomUser()

In [7]:
some_list = r.generate_users(10)
some_list

[<randomuser.RandomUser at 0x115ad2990>,
 <randomuser.RandomUser at 0x115ad2850>,
 <randomuser.RandomUser at 0x115d7f820>,
 <randomuser.RandomUser at 0x115d7f950>,
 <randomuser.RandomUser at 0x115aab650>,
 <randomuser.RandomUser at 0x112dcaf10>,
 <randomuser.RandomUser at 0x112dc9e10>,
 <randomuser.RandomUser at 0x112ba7650>,
 <randomuser.RandomUser at 0x115b0b150>,
 <randomuser.RandomUser at 0x115b2a6c0>]

In [9]:
name = r.get_full_name()
name

'Amanda Morris'

In [11]:
for user in some_list:
    print(f'{user.get_full_name()} {user.get_email()}')

Aristóteles Teixeira aristoteles.teixeira@example.com
Adrian Clark adrian.clark@example.com
Alice Banks alice.banks@example.com
Nooa Heinonen nooa.heinonen@example.com
Oliver Lam oliver.lam@example.com
Amber Lucas amber.lucas@example.com
Inmaculada Carmona inmaculada.carmona@example.com
Claudia Reed claudia.reed@example.com
النا حسینی ln.hsyny@example.com
Vincent Slawa vincent.slawa@example.com

In [15]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})

    print(users)
    return pd.DataFrame(users)

In [16]:
df1 = get_users()
df1

[{'Name': 'Mario Blanco', 'Gender': 'male', 'City': 'Lorca', 'State': 'Andalucía', 'Email': 'mario.blanco@example.com', 'DOB': '1990-06-12T09:25:33.317Z', 'Picture': 'https://randomuser.me/api/portraits/men/76.jpg'}, {'Name': 'Marie Curtis', 'Gender': 'female', 'City': 'Alexandria', 'State': 'West Virginia', 'Email': 'marie.curtis@example.com', 'DOB': '1987-07-21T06:05:50.499Z', 'Picture': 'https://randomuser.me/api/portraits/women/74.jpg'}, {'Name': 'Emre Akyüz', 'Gender': 'male', 'City': 'Kars', 'State': 'Kırşehir', 'Email': 'emre.akyuz@example.com', 'DOB': '1987-01-16T23:08:59.413Z', 'Picture': 'https://randomuser.me/api/portraits/men/20.jpg'}, {'Name': 'Alkan Van Harten', 'Gender': 'male', 'City': 'Valkkoog', 'State': 'Zuid-Holland', 'Email': 'alkan.vanharten@example.com', 'DOB': '1967-01-05T20:17:05.766Z', 'Picture': 'https://randomuser.me/api/portraits/men/89.jpg'}, {'Name': 'Guillermo Garcia', 'Gender': 'male', 'City': 'Santiago de Compostela', 'State': 'Región de Murcia', 'Email': 'guillermo.garcia@example.com', 'DOB': '1973-04-30T20:03:11.406Z', 'Picture': 'https://randomuser.me/api/portraits/men/3.jpg'}, {'Name': 'Francis Van der Reijden', 'Gender': 'female', 'City': 'Kudelstaart', 'State': 'Gelderland', 'Email': 'francis.vanderreijden@example.com', 'DOB': '1959-01-08T09:43:53.450Z', 'Picture': 'https://randomuser.me/api/portraits/women/7.jpg'}, {'Name': 'Albane Fernandez', 'Gender': 'female', 'City': 'Pau', 'State': 'Seine-Maritime', 'Email': 'albane.fernandez@example.com', 'DOB': '1946-05-14T08:26:17.365Z', 'Picture': 'https://randomuser.me/api/portraits/women/68.jpg'}, {'Name': 'Celina Philippe', 'Gender': 'female', 'City': 'Wiler (Lötschen)', 'State': 'Neuchâtel', 'Email': 'celina.philippe@example.com', 'DOB': '1961-02-19T13:59:19.141Z', 'Picture': 'https://randomuser.me/api/portraits/women/44.jpg'}, {'Name': 'Olivia Barnaby', 'Gender': 'female', 'City': 'Charlottetown', 'State': 'New Brunswick', 'Email': 'olivia.barnaby@example.com', 'DOB': '1977-04-26T02:02:50.312Z', 'Picture': 'https://randomuser.me/api/portraits/women/23.jpg'}, {'Name': 'Lucas Ranheim', 'Gender': 'male', 'City': 'Porsgrunn', 'State': 'Aust-Agder', 'Email': 'lucas.ranheim@example.com', 'DOB': '1952-03-19T07:52:46.915Z', 'Picture': 'https://randomuser.me/api/portraits/men/78.jpg'}]

,Name,Gender,City,State,Email,DOB,Picture
0,Mario Blanco,male,Lorca,Andalucía,mario.blanco@example.com,1990-06-12T09:25:33.317Z,https://randomuser.me/api/portraits/men/76.jpg
1,Marie Curtis,female,Alexandria,West Virginia,marie.curtis@example.com,1987-07-21T06:05:50.499Z,https://randomuser.me/api/portraits/women/74.jpg
2,Emre Akyüz,male,Kars,Kırşehir,emre.akyuz@example.com,1987-01-16T23:08:59.413Z,https://randomuser.me/api/portraits/men/20.jpg
3,Alkan Van Harten,male,Valkkoog,Zuid-Holland,alkan.vanharten@example.com,1967-01-05T20:17:05.766Z,https://randomuser.me/api/portraits/men/89.jpg
4,Guillermo Garcia,male,Santiago de Compostela,Región de Murcia,guillermo.garcia@example.com,1973-04-30T20:03:11.406Z,https://randomuser.me/api/portraits/men/3.jpg
5,Francis Van der Reijden,female,Kudelstaart,Gelderland,francis.vanderreijden@example.com,1959-01-08T09:43:53.450Z,https://randomuser.me/api/portraits/women/7.jpg
6,Albane Fernandez,female,Pau,Seine-Maritime,albane.fernandez@example.com,1946-05-14T08:26:17.365Z,https://randomuser.me/api/portraits/women/68.jpg
7,Celina Philippe,female,Wiler (Lötschen),Neuchâtel,celina.philippe@example.com,1961-02-19T13:59:19.141Z,https://randomuser.me/api/portraits/women/44.jpg
8,Olivia Barnaby,female,Charlottetown,New Brunswick,olivia.barnaby@example.com,1977-04-26T02:02:50.312Z,https://randomuser.me/api/portraits/women/23.jpg
9,Lucas Ranheim,male,Porsgrunn,Aust-Agder,lucas.ranheim@example.com,1952-03-19T07:52:46.915Z,https://randomuser.me/api/portraits/men/78.jpg

In [18]:
import requests
import json

In [19]:
data = requests.get('https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all')

In [23]:
results = json.loads(data.text)
results[0:2]

[{'name': 'Persimmon',
  'id': 52,
  'family': 'Ebenaceae',
  'order': 'Rosales',
  'genus': 'Diospyros',
  'nutritions': {'calories': 81,
   'fat': 0.0,
   'sugar': 18.0,
   'carbohydrates': 18.0,
   'protein': 0.0}},
 {'name': 'Strawberry',
  'id': 3,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Fragaria',
  'nutritions': {'calories': 29,
   'fat': 0.4,
   'sugar': 5.4,
   'carbohydrates': 5.5,
   'protein': 0.8}}]

In [26]:
df2 = pd.DataFrame(results)
df2.head()

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."

In [29]:
df2 = pd.json_normalize(results)
df2.head()

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.0,18.0,18.0,0.0
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.4,5.4,5.5,0.8
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.2,17.2,22.0,1.0
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.2,2.6,3.9,0.9
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.1,10.0,15.0,0.4

In [38]:
row_c = df2.loc[df2["name"] == "Cherry"]
(row_c.iloc[0]['family'], row_c.iloc[0]['genus'])

('Rosaceae', 'Prunus')