In [1]:
import pandas as pd

In [3]:
data = [10, 20, 30, 40, 50]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
print(s[2])
print(s.iloc[3])
print(s[1:4])

30
40
1    20
2    30
3    40
dtype: int64

In [8]:
# Creating a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 28],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']}
df = pd.DataFrame(data)
print(df)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

In [11]:
print(df['Name'])

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: str

In [13]:
print(df.iloc[2])   # Access the third row by position
print('==========')
print(df.loc[1])    # Access the second row by label

Name        Charlie
Age              35
City    Los Angeles
Name: 2, dtype: object
==========
Name              Bob
Age                30
City    San Francisco
Name: 1, dtype: object

In [14]:
print(df[['Name', 'Age']])  # Select specific columns
print('='*20)
print(df[1:3])             # Select specific rows

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   28
====================
      Name  Age           City
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

In [17]:
unique_dates = df['Age'].unique()
unique_dates

array([25, 30, 35, 28])

In [18]:
high_above_102 = df[df['Age'] > 25]
high_above_102

      Name  Age           City
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

In [20]:
#Define a dictionary 'x'

x = {'Name': ['Rose','John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
      'Salary':[100000, 80000, 50000, 60000]}
# Casting dictionary to a DataFrame
df = pd.DataFrame(x)

# Display the result of pd
df

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [21]:
#Retrieving the "ID" column and assigning it to a variable x
x = df[['ID']]
x

   ID
0   1
1   2
2   3
3   4

In [22]:
#check the type of x
type(x)

pandas.DataFrame

In [23]:
#Retrieving the Department, Salary and ID columns and assigning it to a variable z

z = df[['Department','Salary','ID']]
z

        Department  Salary  ID
0  Architect Group  100000   1
1   Software Group   80000   2
2      Design Team   50000   3
3   Infrastructure   60000   4

In [25]:
students = {
    'Student': ['David', 'Samuel', 'Terry', 'Evan'],
    'Age': [27, 24, 22, 32],
    'Country': ['UK', 'Canada', 'China', 'USA'],
    'Course': ['Python', 'Data Structures', 'Machine Learning', 'Web Development'],
    'Marks': [85, 72, 89, 76]
}

df1 = pd.DataFrame(students)
print(df1)

  Student  Age Country            Course  Marks
0   David   27      UK            Python     85
1  Samuel   24  Canada   Data Structures     72
2   Terry   22   China  Machine Learning     89
3    Evan   32     USA   Web Development     76

In [30]:
b = df1[['Marks']]
b

   Marks
0     85
1     72
2     89
3     76

In [29]:
c = df1[['Country', 'Course']]
c

  Country            Course
0      UK            Python
1  Canada   Data Structures
2   China  Machine Learning
3     USA   Web Development

In [31]:
x = df1['Student']
print(x)
print(type(x))

0     David
1    Samuel
2     Terry
3      Evan
Name: Student, dtype: str
<class 'pandas.Series'>

In [34]:
df

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [35]:
df.iloc[0, 0]

'Rose'

In [36]:
df.iloc[0, 2]

'Architect Group'

In [37]:
df.loc[0, 'Salary']

np.int64(100000)

In [38]:
df2=df
df2=df2.set_index("Name")
df2

      ID       Department  Salary
Name
Rose   1  Architect Group  100000
John   2   Software Group   80000
Jane   3      Design Team   50000
Mary   4   Infrastructure   60000

In [40]:
df2.head()

      ID       Department  Salary
Name
Rose   1  Architect Group  100000
John   2   Software Group   80000
Jane   3      Design Team   50000
Mary   4   Infrastructure   60000

In [42]:
df2.loc['Rose', 'ID']

np.int64(1)

In [44]:
df2.iloc[2, 1]

'Design Team'

In [45]:
print(df2.loc['Jane', 'Department'])

Design Team

In [49]:
print(df2.iloc[3, 2])

60000

In [51]:
# let us do the slicing using old dataframe df

df.iloc[0:2, 0:3]

   Name  ID       Department
0  Rose   1  Architect Group
1  John   2   Software Group

In [52]:
#let us do the slicing using loc() function on old dataframe df where index column is having labels as 0,1,2
df.loc[0:2,'ID':'Department']

   ID       Department
0   1  Architect Group
1   2   Software Group
2   3      Design Team

In [53]:
#let us do the slicing using loc() function on new dataframe df2 where index column is Name having labels: Rose, John and Jane
df2.loc['Rose':'Jane', 'ID':'Department']

      ID       Department
Name
Rose   1  Architect Group
John   2   Software Group
Jane   3      Design Team